### PR TITLE
Keybord Inputs can't be nil, Configurable Smoke and Configurable max members in crew

### PR DESCRIPTION
**Pull request by Flozii**
KeybordInputs could be nil (it returned "")
Config for smoke
Configurable max members in crew and the limit is working when you recruit someone (Line 4 in cl_crew_main)

### CODE REVIEW

**Comment by Rubylium** [comment]
Good PR !
The only issue is, you are exposing the config to client side that contain sensitive data like webhook. I can not accepte this :/

All others things looks good to me, did all of this got tested ?

**Comment by Flozii** [comment]
Thanks,
The best way would be to create a server side config and a client side config. 

And yes, I tested everything, it's working

**Comment by Rubylium** [comment]
Mmh on the fxmanifest you did rename the server side config to sv_config but didn’t rename the actual file, it’s still config.lua, I don’t think it’s intended :D

**Comment by Flozii** [comment]
What do you mean ? I renamed the old config file to config_sv and created the file config_cl

 image

**Comment by Rubylium** [comment]
Oh my bad ! GitHub was playing tricks on me I didn’t see the rename haha !
All good for me :)

**Pull request merged**
